name: Code Review
on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
      - master

jobs:
  claude-review:
    uses: E3KCO/github-workflows/.github/workflows/claude-code-review.yml@main
    secrets:
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}